stages:
  - tests

taiko:
  stage: tests
  image: taiko:latest
  variables:
    TAIKO_BROWSER_ARGS: '--no-sandbox,--start-maximized,--disable-dev-shm-usage'
  script:
    - taiko tests/taiko-test-1.js
