FROM oven/bun:1-alpine

LABEL org.opencontainers.image.title="taiko-ci" \
      org.opencontainers.image.description="Taiko web browser test runner in Gitlab CI" \
      org.opencontainers.image.source="https://github.com/t0mmili/taiko-ci" \
      org.opencontainers.image.version="1-bun" \
      org.opencontainers.image.licenses="MIT"

      # Install Chromium and dependencies
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    udev

ENV PATH="$PATH:/root/.bun/bin" \
    TAIKO_BROWSER_PATH=/usr/bin/chromium \
    TAIKO_SKIP_CHROMIUM_DOWNLOAD=true

# Install Taiko
RUN bun install -g taiko
