FROM node:lts-alpine

LABEL org.opencontainers.image.title="taiko-ci" \
      org.opencontainers.image.description="Taiko web browser test runner in Gitlab CI" \
      org.opencontainers.image.source="https://github.com/t0mmili/taiko-ci" \
      org.opencontainers.image.version="1-npm" \
      org.opencontainers.image.licenses="MIT"

# Install Chromium and dependencies
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    udev

ENV TAIKO_BROWSER_PATH=/usr/bin/chromium \
    TAIKO_SKIP_CHROMIUM_DOWNLOAD=true

# Install Taiko
RUN npm install -g taiko
